name: CI/CD - Saudações Aleatórias

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Lint code
        run: go fmt ./...

  test:
    runs-on: ubuntu-latest
    needs: build-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        run: go test ./...

  docker-build-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/ms-saudacoes-aleatorias:latest

  deploy-koyeb:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Deploy to Koyeb via API
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          curl -X PATCH https://app.koyeb.com/v1/services/f6ba0ac3-2e15-4603-91ac-13cd01eb1245/update \
            -H "Authorization: Bearer $KOYEB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "image": "'"$DOCKER_USER/ms-saudacoes-aleatorias:latest"'"
            }'

